防block,随机打卡时间，增加本地自助打卡，无需github workflow
Violin9906/URC-ncov-AutoReport pull request #6
Opened 2020-08-31 10:20 UTC by lyciumlee

2020-08-31 13:18 UTC, Violin9906 commented on set_crontab.py
> +MY_COMMOND = "python " + CURRENT_DIR + "/report.py" + " " + CURRENT_DIR + "/data_west.json" + " " + '\"' + STUID + '\"' + " " + '\"' + STUID_PASSWORD + '\"'
请将data_west.json替换为data.json。为了代码的一致性，不建议直接使用模板文件。

2020-08-31 13:19 UTC, Violin9906 commented on report.py
> +import random
请确认requirements.txt中包含新引入的依赖项

2020-08-31 13:20 UTC, Violin9906 commented on README.md
> +要在本地运行测试，需要安装python 3。我们假设您已经安装了python 3和pip 3，并已将其路径添加到环境变量。
希望提供更完整的使用说明（比如在本地运行需要电脑不关机），使用者中不乏对计算机一窍不通的学生。

2020-08-31 13:22 UTC, Violin9906 commented on set_crontab.py
> +job.setall( str(random.randint(1, 60)) + " "+ "7-22 * * *")
似乎你的代码每小时都打一次卡？请确认这样做的合理性。

2020-08-31 13:23 UTC, Violin9906 commented on set_crontab.py
> +import random
请确认requirements.txt中包含新引入的依赖项

2020-08-31 13:26 UTC, Violin9906 requested changes
- 希望提供更完整的使用说明。
- 请在requirements.txt中添加依赖项。
- 其它的一些小tips。

2020-09-01 06:07 UTC, lyciumlee commented
nb！看的好细致，哈哈哈哈

2020-10-30 09:04 UTC, closed without merging